env: "local"
migrations_path: "file://./migrations"
http_server:
  host: "localhost"
  port: 8080
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "pr_manager_db"
  ssl_mode: "disable"